extensions:
  client:
    endpoints:
      - wss://rpc.hydradx.cloud
  event_bus:
  substrate_api:
    stale_timeout_seconds: 180
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 60
    default_size: 500
  merge_subscription:
    keep_alive_seconds: 60
  server:
    port: 9944
    listen_address: '0.0.0.0'
    max_connections: 2000
    http_methods:
      - path: /health
        method: system_health
      - path: /liveness
        method: chain_getBlockHash
    cors: all
  rate_limit:
    connection:
      burst: 100
      period_secs: 1
    ip:
      burst: 500
      period_secs: 10
    use_xff: true

middlewares:
  methods:
    - delay
    - response
    - inject_params
    - cache
    - upstream
  subscriptions:
    - merge_subscription
    - upstream

rpcs: everything
