extensions:  
  client:
    endpoints:
      - wss://eth-rpc-karura-testnet.aca-staging.network
  event_bus:
  eth_api:
    stale_timeout_seconds: 180 # rotate endpoint if no new blocks for 3 minutes
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 60
    default_size: 500
  server:
    port: 8545
    listen_address: '0.0.0.0'
    max_connections: 2000
    max_batch_size: 10
    cors: all
  # rate_limit is disabled by default. Uncomment and adjust to enable it.
  # rate_limit:
  #   connection:
  #     burst: ${RATE_LIMIT_CONNECTION_BURST:-400}
  #     period_secs: ${RATE_LIMIT_CONNECTION_PERIOD_SECS:-1}
  #   ip:
  #     burst: ${RATE_LIMIT_IP_BURST:-2000}
  #     period_secs: ${RATE_LIMIT_IP_PERIOD_SECS:-10}
  #   # use X-Forwarded-For header to get real ip, if available (e.g. behind a load balancer).
  #   # WARNING: Use with caution, as this xff header can be forged.
  #   use_xff: true # default is false
  #   xff_header: ${XFF_HEADER:-x-forwarded-for}

middlewares:
  methods:
    - response
    - block_tag
    - cache
    - submission_tracker
    - upstream
  subscriptions:
    - upstream

rpcs: ethereum
